---
# Reference: https://yamllint.readthedocs.io/en/stable/configuration.html
extends: default
ignore: |
  pnpm-lock.yaml
rules:
  line-length:
    max: 140
    level: warning
  truthy:
    allowed-values: ['true', 'false']
    check-keys: false
