---
packages:
  - packages/book
  - packages/fp
  - packages/fp-zod
  - packages/pure
  - packages/nest-sample
  - packages/hono-drizzle
onlyBuiltDependencies:
  - '@nestjs/core'
  - esbuild
  - unrs-resolver
